[default]
# be verbose
verbose=1
# testing database
notebooks_db=notebooks-test.db

[VO]

[prometheus]

[eosc]
accounting_url=https://api.acc.eosc.example.com
# Installation that metrics are reported for
installation_id=test-site
timestamp_file=eosc-accounting-test.timestamp

[eosc.flavors]
# add every flavor to be reported as follows
flava=id_flava
