---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounting
data:
  config.ini: |
    [default]
    {{- if .Values.accounting.sitename }}
    site={{ .Values.accounting.sitename }}
    {{- else }}
    # site=EGI-NOTEBOOKS
    {{- end }}
    {{- if .Values.accounting.cloudType }}
    cloud_type={{ .Values.accounting.cloudType }}
    {{- else }}
    # cloud_type=EGI Notebooks
    {{- end }}
    {{- if .Values.accounting.service }}
    cloud_compute_service={{ .Values.accounting.service }}
    {{- else }}
    # cloud_compute_service=
    {{- end }}
    {{- if.Values.debug }}
    verbose=1
    {{- end }}
    {{- if .Values.storage.apelSpool }}
    apel_spool={{ .Values.storage.apelSpool }}
    {{- else }}
    # apel_spool=
    {{- end }}
    {{- if .Values.storage.notebooksDb }}
    notebooks_db={{ .Values.storage.notebooksDb }}
    {{- else }}
    # notebooks_db=
    {{- end }}

    [prometheus]
    {{- if .Values.prometheus.url }}
    url={{ .Values.prometheus.url }}
    {{- else }}
    # url=http://localhost:8080
    {{- end }}
    # user=
    # password=
    # verify=0
    # filter=pod=~'jupyter-.*'
    range=24h

    # mapping from k8s namespace to VO
    [VO]
    {{- range $key, $val := .Values.accounting.fqan }}
    {{ $key }}={{ $val }}
    {{- end }}

    # EOSC accounting
    [eosc]
    {{- if .Values.eosc.tokenUrl }}
    token_url={{ .Values.eosc.tokenUrl }}
    {{- end }}
    {{- if .Values.eosc.clientSecret }}
    client_secret={{ .Values.eosc.clientSecret }}
    {{- end }}
    {{- if .Values.eosc.clientId }}
    client_id={{ .Values.eosc.clientId }}
    {{- end }}
    {{- if .Values.eosc.accountingUrl }}
    accounting_url={{ .Values.eosc.accountingUrl }}
    {{- end }}
    {{- if .Values.eosc.installationId }}
    installation_id={{ .Values.eosc.installationId }}
    {{- end }}
    {{- if .Values.storage.timestamp }}
    timestamp_file={{ .Values.storage.timestamp }}
    {{- end }}

    [eosc.flavors]
    {{- range $key, $val := .Values.eosc.flavorMetrics }}
    {{ $key }}={{ $val }}
    {{- end }}
