name: Release Charts

jobs:
  release:
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --get user.name
          git config --get user.email

      - name: Install Helm
        run: |
          curl -ssL https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz | tar -xz -C . --strip-components 1 linux-amd64/helm
          sudo install -m 0755 -o root -g root helm /usr/local/bin/

      - name: Install Python depedencies
        run: |
          sudo apt-get install --no-install-recommends -y python3 python3-pip
          sudo pip install -r dev-requirements.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run chartpress
        run: |
          REMOTE_ORIGIN="https://x-access-token:${{ github.token }}@$(git remote get-url origin | sed 's,^[^/]*//,,')"; sed -i chartpress.yaml -e "s,git:.*,git: $REMOTE_ORIGIN,"
          cat chartpress.yaml
          chartpress --push --publish-chart
