---
name: Unit tests

on: [pull_request, push]

jobs:
  python-pytest:
    name: Python unittests using pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # Full git history needed to get proper list of changed files
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Test with pytest
        run: |
          pytest -v --log-cli-level=INFO
